### ISSUE TITLE
Security of source("https://install-github.me/dreamRs/wired") in your readme.md

### ISSUE THREAD

**Issue by mhoehle** [dreamRs/wired#1]
Not sure I would trust to run a script just like this. Could contain all kinds of nasty commands, see e.g. https://rud.is/b/2017/02/23/on-watering-holes-trust-defensible-systems-and-data-science-community-security/
Maybe just remove this option?

**Comment by pvictor** [comment]
`https://install-github.me` is a service based on package `remotes` (written by Gábor Csárdi and RStudio), please check package README for more details: https://github.com/r-lib/remotes

**Comment by mhoehle** [comment]
Ok, thanks for clarifying. I just went to https://install-github.me and didn't see much there...
![image](https://user-images.githubusercontent.com/5960279/41657441-a727d17c-7493-11e8-8b2e-7be6e1c077b6.png)

**Comment by pvictor** [comment]
Yes I understand your concern, this is not the traditionnal way to install a package from Github.. I've updated the README to be more clear.

Thanks,

Victor

**Comment by mhoehle** [comment]
Thanks!
